name: Bug report
description: For issues with running openpilot on your comma device
labels: ["bug"]
body:

  - type: markdown
    attributes:
      value: >
        Before creating a **bug report**, please check the following:
          * If the issue likely only affects your car model or make, go back and open a **car bug report** instead.
          * Ensure you're running the latest openpilot release.
          * Ensure you're using officially supported hardware. Issues running on PCs have a different issue template.
          * Ensure there isn't an existing issue for your bug. If there is, leave a comment on the existing issue.
          * Ensure you're running stock openpilot. We cannot look into bug reports from forks.

  - type: textarea
    attributes:
      label: Describe the bug
      description: Also include a description of how to reproduce the bug
    validations:
      required: true

  - type: input
    id: route
    attributes:
      label: Provide a route where the issue occurs
      description: We cannot look into issues without routes.
      placeholder: 77611a1fac303767|2020-05-11--16-37-07
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: openpilot version
      description: If you're not on release, provide the commit hash
      placeholder: 0.8.10
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional info

